In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/transactions.csv')
print(df.head())

         Date        Category                   Description   Amount     Type
0  2023-01-01          Salary                Monthly salary  2224.84   Income
1  2023-01-01   Entertainment        Movies, concerts, etc.   416.39  Expense
2  2023-01-02  Transportation  Fuel, public transport, etc.    28.61  Expense
3  2023-01-05  Transportation  Fuel, public transport, etc.    48.12  Expense
4  2023-01-06  Transportation  Fuel, public transport, etc.    37.47  Expense

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 536 entries, 0 to 535
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         536 non-null    str
 1   Category     536 non-null    str
 2   Description  536 non-null    str
 3   Amount       536 non-null    float64
 4   Type         536 non-null    str
dtypes: float64(1), str(4)
memory usage: 21.1 KB

In [4]:
df['Date'] = pd.to_datetime(df['Date'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 536 entries, 0 to 535
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         536 non-null    datetime64[us]
 1   Category     536 non-null    str
 2   Description  536 non-null    str
 3   Amount       536 non-null    float64
 4   Type         536 non-null    str
dtypes: datetime64[us](1), float64(1), str(3)
memory usage: 21.1 KB

In [5]:
df = df.set_index('Date')
df.head()

                  Category                   Description   Amount     Type
Date
2023-01-01          Salary                Monthly salary  2224.84   Income
2023-01-01   Entertainment        Movies, concerts, etc.   416.39  Expense
2023-01-02  Transportation  Fuel, public transport, etc.    28.61  Expense
2023-01-05  Transportation  Fuel, public transport, etc.    48.12  Expense
2023-01-06  Transportation  Fuel, public transport, etc.    37.47  Expense

In [7]:
monthly_totals = df['Amount'].resample('ME').sum()
monthly_totals.head(12)

Date
2023-01-31    4436.02
2023-02-28    3761.33
2023-03-31    5833.98
2023-04-30    3899.96
2023-05-31    3711.49
2023-06-30    4207.18
2023-07-31    4363.81
2023-08-31    5538.53
2023-09-30    3892.46
2023-10-31    4059.44
2023-11-30    4060.14
2023-12-31    3693.70
Freq: ME, Name: Amount, dtype: float64

In [10]:
df_income = df[df['Type'] == 'Income']
df_expenses = df[df['Type'] == 'Expense']
df_income.head()
df_expenses.head()

                  Category                   Description  Amount     Type
Date
2023-01-01   Entertainment        Movies, concerts, etc.  416.39  Expense
2023-01-02  Transportation  Fuel, public transport, etc.   28.61  Expense
2023-01-05  Transportation  Fuel, public transport, etc.   48.12  Expense
2023-01-06  Transportation  Fuel, public transport, etc.   37.47  Expense
2023-01-08  Transportation  Fuel, public transport, etc.   20.66  Expense

In [11]:
monthly_income = df_income['Amount'].resample('ME').sum()
monthly_expenses = df_expenses['Amount'].resample('ME').sum()
print('Monthly Income:')
print(monthly_income.head(12))
print('Monthly Expenses:')
print(monthly_expenses.head(12))

Monthly Income:
Date
2023-01-31    2224.84
2023-02-28    2193.09
2023-03-31    2909.51
2023-04-30    2173.09
2023-05-31    2721.21
2023-06-30    2643.87
2023-07-31    2596.59
2023-08-31    2988.91
2023-09-30    2211.55
2023-10-31    2159.55
2023-11-30    2318.21
2023-12-31    2412.00
Freq: ME, Name: Amount, dtype: float64
Monthly Expenses:
Date
2023-01-31    2211.18
2023-02-28    1568.24
2023-03-31    2924.47
2023-04-30    1726.87
2023-05-31     990.28
2023-06-30    1563.31
2023-07-31    1767.22
2023-08-31    2549.62
2023-09-30    1680.91
2023-10-31    1899.89
2023-11-30    1741.93
2023-12-31    1281.70
Freq: ME, Name: Amount, dtype: float64

In [12]:
monthly_net = monthly_income - monthly_expenses
print('Monthly Net:') 
print(monthly_net.head(12))

Monthly Net:
Date
2023-01-31      13.66
2023-02-28     624.85
2023-03-31     -14.96
2023-04-30     446.22
2023-05-31    1730.93
2023-06-30    1080.56
2023-07-31     829.37
2023-08-31     439.29
2023-09-30     530.64
2023-10-31     259.66
2023-11-30     576.28
2023-12-31    1130.30
Freq: ME, Name: Amount, dtype: float64

In [16]:
category_totals = df_expenses.groupby('Category')['Amount'].sum().sort_values(ascending=False)
print('Category Totals:')
print(category_totals)

Category Totals:
Category
Housing           17733.16
Utilities         14977.79
Entertainment     12835.97
Transportation     9269.02
Groceries          8930.41
Healthcare         3450.26
Name: Amount, dtype: float64